<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Manejo de errores</title>
  </head>
  <body>
    <script>
      /* CALLBACKS
      function sumarNumeros(a, b, callback) {
        setTimeout(function () {
          let respuesta = a + b;
          if (
            typeof a !== "number" ||
            typeof b !== "number" ||
            typeof respuesta !== "number"
          ) {
            return callback(new Error("Algun argumento no es un n√∫mero"));
          }
          callback(null, respuesta);
        }, 1000);
      }

      sumarNumeros(1, 2, function (error, resultado) {
        if (error) {
          console.error(error);
        } else {
          console.log(resultado);
        }
      });*/

      /* PROMESAS
      function sumarNumeros(a, b) {
        return new Promise(function (resolve, reject) {
          setTimeout(function () {
            if (typeof a !== "number" || typeof b !== "number") {
              reject(new Error("Ambos argumentos deben de ser numeros"));
            } else {
              resolve(a + b);
            }
          }, 1000);
        });
      }

      sumarNumeros(1, 2)
        .then(function (resultado) {
          console.log(resultado);
        })
        .catch(function (error) {
          console.error(error);
        });*/

      // ASYNC / AWAIT
      async function sumarNumeros(a, b) {
        if (typeof a !== "number" || typeof b !== "number") {
          throw new Error("Alguno de los argumentos no es numero");
        }
        return a + b;
      }

      async function manejarErrores() {
        try {
          let resultado = await sumarNumeros(2, 3);
          console.log(resultado);
        } catch (error) {
          console.error(error);
        }
      }

      manejarErrores();
    </script>
  </body>
</html>
